// PDF Export Utility for Reports
export const exportReportToPDF = (report, labSettings = {}) => {
  try {
    const element = document.getElementById(`report-print-${report._id}`);
    if (!element) {
      console.error('Report element not found for PDF export');
      return false;
    }

    // Clone the element for printing
    const clonedElement = element.cloneNode(true);
    clonedElement.style.display = 'block';

    // Create a new window for printing
    const printWindow = window.open('', '', 'width=800,height=600');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Report-${report.reportId}.pdf</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
            @media print { body { margin: 0; padding: 10px; } }
            @page { size: A4; margin: 0.5in; }
          </style>
        </head>
        <body>
          ${clonedElement.innerHTML}
          <script>
            window.print();
            setTimeout(() => window.close(), 250);
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
    return true;
  } catch (error) {
    console.error('Error exporting to PDF:', error);
    return false;
  }
};

// Generate PDF filename
export const generatePDFFilename = (report) => {
  const date = new Date(report.reportDate).toISOString().split('T')[0];
  return `Report_${report.reportId}_${report.patient?.patientId}_${date}.pdf`;
};

// Print report directly
export const printReport = (report) => {
  try {
    const element = document.getElementById(`report-print-${report._id}`);
    if (!element) {
      console.error('Report element not found');
      return false;
    }

    const printWindow = window.open('', '', 'width=800,height=600');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Report-${report.reportId}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
            @media print { body { margin: 0; padding: 10px; } }
          </style>
        </head>
        <body>
          ${element.innerHTML}
          <script>
            window.print();
            setTimeout(() => window.close(), 250);
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
    return true;
  } catch (error) {
    console.error('Error printing report:', error);
    return false;
  }
};

// Export report as text
export const exportReportAsText = (report) => {
  const text = `
LABORATORY REPORT
=================

Report ID: ${report.reportId}
Report Date: ${new Date(report.reportDate).toLocaleDateString()}

PATIENT INFORMATION
-------------------
Name: ${report.patient?.name}
Patient ID: ${report.patient?.patientId}
Age: ${report.patient?.age} ${report.patient?.ageUnit}
Gender: ${report.patient?.gender}
Contact: ${report.patient?.phone}

TEST INFORMATION
----------------
Test Name: ${report.test?.name}
Test Category: ${report.test?.category}
Sample Type: ${report.test?.sampleType}

RESULTS
-------
${report.results?.map(r => `${r.parameterName}: ${r.value} ${r.unit} (Normal Range: ${r.normalRange}) ${r.flag ? `[${r.flag}]` : ''}`).join('\n')}

REMARKS
-------
${report.remarks || 'No remarks'}

DOCTOR INFORMATION
------------------
Doctor: ${report.doctor?.name}
Specialty: ${report.doctor?.specialty}

STATUS: ${report.status}
Generated by: ${report.enteredBy?.name || 'N/A'}
${report.verifiedBy ? `Verified by: ${report.verifiedBy.name}` : ''}
  `.trim();

  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = generatePDFFilename(report).replace('.pdf', '.txt');
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export default {
  exportReportToPDF,
  generatePDFFilename,
  printReport,
  exportReportAsText,
};
